name: flutter_mobile_csms
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  get_storage: ^2.1.1
  http: 1.1.0
  path_provider: 2.1.1
  gap: 3.0.1
  multi_dropdown: 2.1.0
  numberpicker: 2.1.2
  loading_overlay_pro: 2.1.1
  image_picker: 1.0.4
  dio: 5.3.4
  accordion: 2.6.0
  intl: 0.19.0
  flutter: 
    sdk: flutter
  syncfusion_flutter_datepicker: ^21.2.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: fonts/Inter.ttf
    - family: Oswald
      fonts: 
        - asset: fonts/Oswald-Regular.ttf
  uses-material-design: true

