// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCis4CUI47fswIX4hMGDyBEBLT6-Xo0LLw',
    appId: '1:240478555085:web:943f5fb894872e8541d284',
    messagingSenderId: '240478555085',
    projectId: 'csms-fcm',
    authDomain: 'csms-fcm.firebaseapp.com',
    storageBucket: 'csms-fcm.appspot.com',
    measurementId: 'G-SKRT173RMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrxq-Sm5Ji0TX0uuJG8EblK0CdSAM_XOA',
    appId: '1:240478555085:android:c6943e9d63bc2ee041d284',
    messagingSenderId: '240478555085',
    projectId: 'csms-fcm',
    storageBucket: 'csms-fcm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz5IOizSGHa03n6_LPUgZizAxhtJoWVag',
    appId: '1:240478555085:ios:06072df1c801ebe941d284',
    messagingSenderId: '240478555085',
    projectId: 'csms-fcm',
    storageBucket: 'csms-fcm.appspot.com',
    iosBundleId: 'com.example.flutterMobileCsms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz5IOizSGHa03n6_LPUgZizAxhtJoWVag',
    appId: '1:240478555085:ios:a8d7037b68cbcdee41d284',
    messagingSenderId: '240478555085',
    projectId: 'csms-fcm',
    storageBucket: 'csms-fcm.appspot.com',
    iosBundleId: 'com.example.flutterMobileCsms.RunnerTests',
  );
}
